### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by IThundxr** [samipourquoi/endtech-additions#7]
![Screenshot from 2021-04-28 19-45-49](https://user-images.githubusercontent.com/74031881/116487236-7b5c3f00-a85d-11eb-96a0-bdd1f7648b9a.png)

so with those mods it crashes me when i try placing signs and other things

**Comment by Syntro42** [comment]
I'm sorry for a very late response on this, but I would like to know if this crash is caused by endtech-additions. Can you see if you still experience a crash with just endtech-additions in your mod folder with no other mods?

**Comment by IThundxr** [comment]
stopped using the mod srry
